### ISSUE TITLE
No. 6 Navbar interactivity

### ISSUE THREAD

**Issue by SirJohn42Walker** [SirJohn42Walker/Capstone-Project#10]
### Value Proposition

**As a** user **I need** to be able to click on the different options in the navbar
**to be able to** navigate between pages.

### Description

<img width="564" alt="Bildschirmfoto 2022-11-29 um 10 58 17" src="https://user-images.githubusercontent.com/111967604/204498209-f616796b-76af-458e-9473-794ddf186fd0.png">

### Acceptance Criteria

- [x] when clicking on one of the options in the navbar it takes the user to the corresponding page (home and profile for now)
- [x] the icon of the active page is optically different 

### Tasks

(for developers team)

- [x] create a new branch
- [x] create an active state for the icons
- [x] use Link to switch between pages

### Sizing/Complexity

**M*
