### ISSUE TITLE
No. 7 Basic Styling

### ISSUE THREAD

**Issue by SirJohn42Walker** [SirJohn42Walker/Capstone-Project#13]
### Value Proposition

**As a** user **I need** the app to be styled at least a little bit
**to be able to** not get a stroke by looking at it.

### Description

Implement a style guide and global colors

### Acceptance Criteria

- [x] The app will be nicer to look at

### Tasks

(for developers team)

- [x] Implement global colors
- [x] Use global colors to style everything that is already implemented
- [x] Import a font
- [x] Use said font

### Sizing/Complexity

**M**
