### ISSUE TITLE
No. 8 First Game Page 

### ISSUE THREAD

**Issue by SirJohn42Walker** [SirJohn42Walker/Capstone-Project#19]
### Value Proposition

**As a** user **I need** to land on a game-page that explains the basics of the game
**to be able to** understand what will be expected from me.

### Description

Landing page under the game button in the navbar wit a few welcome- to the game textboxes and the very first very easy riddle.

### Acceptance Criteria

- [ ] When clicking on the navbar-game icon the start game message should be displayed.
- [ ] There should be a few more textboxes with instructions.
- [ ] The very first challenge should be the pressing of the red button.

### Tasks

(for developers team)

- [ ] create a new branch
- [ ] create the game start message
- [ ] create 3 - 4 more messages
- [ ] create a mode to click through these messages
- [ ] implement the first riddle
- [ ] after the riddle give an option to go to the next riddle / page

### Sizing/Complexity

** L **

**Comment by actyvystom** [comment]
A nice one! 🚀
I just suggest to leave out git workflow tasks from the task list (they should be obvious)
