### ISSUE TITLE
No. 9 Second Game Page

### ISSUE THREAD

**Issue by SirJohn42Walker** [SirJohn42Walker/Capstone-Project#20]
### Value Proposition

**As a** user **I need** a second tutorial lvl inside the game that explains another aspect of the game
**to be able to** get more into the mode of this game.

### Description

![Bildschirmfoto 2022-12-05 um 14 52 25](https://user-images.githubusercontent.com/111967604/205653900-141e81ae-8b9a-4344-97ff-192844b9862b.png)

I want this one to work independently from the users actual input. Only the response should be different depending on whether the input includes any form of the word “Chuck”. If so, it will say “That answer is acceptable”. If not, the answer will say “You’re not the sharpest bulb in the shed, are you? This is gonna be difficult for you...”

### Acceptance Criteria

- [ ] the second challenge is a textquestion
- [ ] whatever you put into the answer field, you will be able to continue
- [ ] depending on the answer there will be a different answer

### Tasks

(for developers team)

- [ ] create a new branch
- [ ] create a riddle with a form that works with any mention of "chuck"

### Sizing/Complexity

** M **

**Comment by actyvystom** [comment]
Hi Sascha,
please try to get more precise with your tasks (and leave out git workflow tasks as mentioned in the previous US).

_depending on the answer there will be a different answer_ sounds a bit misleading, maybe better to distinguish between answer/reaction and message displayed?
