### ISSUE TITLE
No. 1 Tutorial

### ISSUE THREAD

**Issue by SirJohn42Walker** [SirJohn42Walker/Capstone-Project#3]
### Value Proposition

**As a** player **I need** to see a tutorial when I first start the game
**to be able to** broadly understand what I am supposed to do in the game.

### Description

Scribble / design or text

### Acceptance Criteria

- [ ] when clicking the game-button for the first time the tutorial should start.
- [ ] the tutorial is soft, so some things should work even with a wrong answer, just with a harsher response.

### Tasks

(for developers team)

- [ ] Design the Tutorial page

### Sizing/Complexity

**M**
