### ISSUE TITLE
No. 1 Navbar

### ISSUE THREAD

**Issue by SirJohn42Walker** [SirJohn42Walker/Capstone-Project#4]
### Value Proposition

**As a** player **I need** a navbar
**to be able to** navigate the different pages of the game.

### Description

![Bildschirmfoto 2022-11-28 um 10 42 45](https://user-images.githubusercontent.com/111967604/204245492-3d760b58-0423-4331-8297-a9017fec52c6.png)

### Acceptance Criteria

- [ ] There should be a navbar
- [ ] the navbar should be fixed to the bottom of the page
- [ ] The navbar should have 4 icons / buttons
- [ ] A clicked button should be a different color to signify active state for that page.

### Tasks

(for developers team)

- [ ] Create a new branch
- [ ] Code a navbar as component
- [ ] use SVGs as clickable icons
- [ ] Highlight the clicked icon

### Sizing/Complexity

**s**
