### ISSUE TITLE
No. 2 Header

### ISSUE THREAD

**Issue by SirJohn42Walker** [SirJohn42Walker/Capstone-Project#5]
### Value Proposition

**As the** Author **I want** a fixed header on each page
**to be able to** revoke some kind of brand-recognition in the player.

### Description

![Bildschirmfoto 2022-11-28 um 12 14 21](https://user-images.githubusercontent.com/111967604/204264504-e0040683-5fba-41ce-8fdb-193432e4bf5b.png)

**The text is not settled in stone yet.**

### Acceptance Criteria

- [x] There is a header component.
- [x] The header component is fixed to to the top of the page.

### Tasks

(for developers team)

- [x] create a new branch.
- [x] Code the header.
- [x] Fix the header to the top of the page.

### Sizing/Complexity

**S**
