### ISSUE TITLE
No. 3 CSS Reset

### ISSUE THREAD

**Issue by SirJohn42Walker** [SirJohn42Walker/Capstone-Project#7]
### Value Proposition

**As a** Author **I need** a custom CSS reset
**to be able to** use styling without any unwelcome surprises.

### Description

I mean... it's a css reset.

### Acceptance Criteria

- [x] there is a css reset.
- [x] it resets the css.

### Tasks

(for developers team)

- [x] create new branch
- [x] Implement the css reset in styles/GlobalStyles.css

### Sizing/Complexity

**XS**

**Comment by Justus-Becker-Rabbenstein** [comment]
Dear SirJohn42Walker,
I reckon that a path to the file which is subject to be changed (maybe: styles/GlobalStyles.css) should be included in "Tasks (for developers team).
Apart from that I think this is fine.
Your sincerly
Justus

**Comment by SirJohn42Walker** [comment]
Thanks Justus, already done!
