### ISSUE TITLE
No. 4 Welcome Page

### ISSUE THREAD

**Issue by SirJohn42Walker** [SirJohn42Walker/Capstone-Project#8]
### Value Proposition

**As a** user **I need** the first page I land on when starting the game
**to be able to** show me a welcome message that introduces me to the game.

### Description

<img width="337" alt="Bildschirmfoto 2022-11-29 um 10 37 03" src="https://user-images.githubusercontent.com/111967604/204493318-69bccb9b-bf72-4418-8ad8-6b8704245d31.png">

(Note: the two counters in the picture are for later.)

### Acceptance Criteria

- [x] the homepage renders a welcome message
- [x] the homepage is the first page the user lands on

### Tasks

(for developers team)

- [x] create a new branch
- [x] code a welcome message.
- [x] maybe use a reusable component for the container.

### Sizing/Complexity

**S**
