### ISSUE TITLE
No. 5 Profile Page

### ISSUE THREAD

**Issue by SirJohn42Walker** [SirJohn42Walker/Capstone-Project#9]
### Value Proposition

**As a** user **I need** a page on which I can see my personal information and some game-stats
**to be able to** to see how I am doing in the game.

### Description

On the Profile Page should be a few counters that show my game progress, time spent in game and other similar informations. Also, a darkmode toggle. All of which should be dummy data / functionalities for now.

### Acceptance Criteria

- [ ] there is a page called 'profile page' 
- [ ] on that page there are a few dummy entries for counters.

### Tasks

(for developers team)

- [ ] create a new branch
- [ ] create the Profile Page
- [ ] Fill the Profile Page with dummy data
- [ ] use reusable components for the textboxes

### Sizing/Complexity

**M**
